# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20171220_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tags', to='products.Product'),
        ),
    ]
